version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: inbola_postgres
    restart: always
    environment:
      POSTGRES_USER: inbola_user
      POSTGRES_PASSWORD: inbola_password
      POSTGRES_DB: inbola_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inbola_network

  redis:
    image: redis:7-alpine
    container_name: inbola_redis
    restart: always
    command: redis-server --requirepass inbola_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - inbola_network

volumes:
  postgres_data:
  redis_data:

networks:
  inbola_network:
    driver: bridge
